export type HeaderSpecificationMap = Map<string, number | number[]>;
export const DxfHeaderSpecification: HeaderSpecificationMap = new Map();

DxfHeaderSpecification.set('$ACADMAINTVER', 70);
DxfHeaderSpecification.set('$ACADVER', 1);
DxfHeaderSpecification.set('$ANGBASE', 50);
DxfHeaderSpecification.set('$ANGDIR', 70);
DxfHeaderSpecification.set('$ATTMODE', 70);
DxfHeaderSpecification.set('$AUNITS', 70);
DxfHeaderSpecification.set('$AUPREC', 70);
DxfHeaderSpecification.set('$CECOLOR', 62);
DxfHeaderSpecification.set('$CELTSCALE', 40);
DxfHeaderSpecification.set('$CELTYPE', 6);
DxfHeaderSpecification.set('$CELWEIGHT', 370);
DxfHeaderSpecification.set('$CEPSNID', 390);
DxfHeaderSpecification.set('$CEPSNTYPE', 380);
DxfHeaderSpecification.set('$CHAMFERA', 40);
DxfHeaderSpecification.set('$CHAMFERB', 40);
DxfHeaderSpecification.set('$CHAMFERC', 40);
DxfHeaderSpecification.set('$CHAMFERD', 40);
DxfHeaderSpecification.set('$CLAYER', 8);
DxfHeaderSpecification.set('$CMLJUST', 70);
DxfHeaderSpecification.set('$CMLSCALE', 40);
DxfHeaderSpecification.set('$CMLSTYLE', 2);
DxfHeaderSpecification.set('$CSHADOW', 280);
DxfHeaderSpecification.set('$DIMADEC', 70);
DxfHeaderSpecification.set('$DIMALT', 70);
DxfHeaderSpecification.set('$DIMALTD', 70);
DxfHeaderSpecification.set('$DIMALTF', 40);
DxfHeaderSpecification.set('$DIMALTRND', 40);
DxfHeaderSpecification.set('$DIMALTTD', 70);
DxfHeaderSpecification.set('$DIMALTTZ', 70);
DxfHeaderSpecification.set('$DIMALTU', 70);
DxfHeaderSpecification.set('$DIMALTZ', 70);
DxfHeaderSpecification.set('$DIMAPOST', 1);
DxfHeaderSpecification.set('$DIMASO', 70);
DxfHeaderSpecification.set('$DIMASSOC', 280);
DxfHeaderSpecification.set('$DIMASZ', 40);
DxfHeaderSpecification.set('$DIMATFIT', 70);
DxfHeaderSpecification.set('$DIMAUNIT', 70);
DxfHeaderSpecification.set('$DIMAZIN', 70);
DxfHeaderSpecification.set('$DIMBLK', 1);
DxfHeaderSpecification.set('$DIMBLK1', 1);
DxfHeaderSpecification.set('$DIMBLK2', 1);
DxfHeaderSpecification.set('$DIMCEN', 40);
DxfHeaderSpecification.set('$DIMCLRD', 70);
DxfHeaderSpecification.set('$DIMCLRE', 70);
DxfHeaderSpecification.set('$DIMCLRT', 70);
DxfHeaderSpecification.set('$DIMDEC', 70);
DxfHeaderSpecification.set('$DIMDLE', 40);
DxfHeaderSpecification.set('$DIMDLI', 40);
DxfHeaderSpecification.set('$DIMDSEP', 70);
DxfHeaderSpecification.set('$DIMEXE', 40);
DxfHeaderSpecification.set('$DIMEXO', 40);
DxfHeaderSpecification.set('$DIMFAC', 40);
DxfHeaderSpecification.set('$DIMGAP', 40);
DxfHeaderSpecification.set('$DIMJUST', 70);
DxfHeaderSpecification.set('$DIMLDRBLK', 1);
DxfHeaderSpecification.set('$DIMLFAC', 40);
DxfHeaderSpecification.set('$DIMLIM', 70);
DxfHeaderSpecification.set('$DIMLUNIT', 70);
DxfHeaderSpecification.set('$DIMLWD', 70);
DxfHeaderSpecification.set('$DIMLWE', 70);
DxfHeaderSpecification.set('$DIMPOST', 1);
DxfHeaderSpecification.set('$DIMRND', 40);
DxfHeaderSpecification.set('$DIMSAH', 70);
DxfHeaderSpecification.set('$DIMSCALE', 40);
DxfHeaderSpecification.set('$DIMSD1', 70);
DxfHeaderSpecification.set('$DIMSD2', 70);
DxfHeaderSpecification.set('$DIMSE1', 70);
DxfHeaderSpecification.set('$DIMSE2', 70);
DxfHeaderSpecification.set('$DIMSHO', 70);
DxfHeaderSpecification.set('$DIMSOXD', 70);
DxfHeaderSpecification.set('$DIMSTYLE', 2);
DxfHeaderSpecification.set('$DIMTAD', 70);
DxfHeaderSpecification.set('$DIMTDEC', 70);
DxfHeaderSpecification.set('$DIMTFAC', 40);
DxfHeaderSpecification.set('$DIMTIH', 70);
DxfHeaderSpecification.set('$DIMTIX', 70);
DxfHeaderSpecification.set('$DIMTM', 40);
DxfHeaderSpecification.set('$DIMTMOVE', 70);
DxfHeaderSpecification.set('$DIMTOFL', 70);
DxfHeaderSpecification.set('$DIMTOH', 70);
DxfHeaderSpecification.set('$DIMTOL', 70);
DxfHeaderSpecification.set('$DIMTOLJ', 70);
DxfHeaderSpecification.set('$DIMTP', 40);
DxfHeaderSpecification.set('$DIMTSZ', 40);
DxfHeaderSpecification.set('$DIMTVP', 40);
DxfHeaderSpecification.set('$DIMTXSTY', 7);
DxfHeaderSpecification.set('$DIMTXT', 40);
DxfHeaderSpecification.set('$DIMTZIN', 70);
DxfHeaderSpecification.set('$DIMUPT', 70);
DxfHeaderSpecification.set('$DIMZIN', 70);
DxfHeaderSpecification.set('$DISPSILH', 70);
DxfHeaderSpecification.set('$DRAGVS', 349);
DxfHeaderSpecification.set('$DWGCODEPAGE', 3);
DxfHeaderSpecification.set('$ELEVATION', 40);
DxfHeaderSpecification.set('$ENDCAPS', 280);
DxfHeaderSpecification.set('$EXTMAX', [10, 20, 30]);
DxfHeaderSpecification.set('$EXTMIN', [10, 20, 30]);
DxfHeaderSpecification.set('$EXTNAMES', 290);
DxfHeaderSpecification.set('$FILLETRAD', 40);
DxfHeaderSpecification.set('$FILLMODE', 70);
DxfHeaderSpecification.set('$FINGERPRINTGUID', 2);
DxfHeaderSpecification.set('$HALOGAP', 280);
DxfHeaderSpecification.set('$HANDSEED', 5);
DxfHeaderSpecification.set('$HIDETEXT', 290);
DxfHeaderSpecification.set('$HYPERLINKBASE', 1);
DxfHeaderSpecification.set('$INDEXCTL', 280);
DxfHeaderSpecification.set('$INSBASE', [10, 20, 30]);
DxfHeaderSpecification.set('$INSUNITS', 70);
DxfHeaderSpecification.set('$INTERFERECOLOR', 62);
DxfHeaderSpecification.set('$INTERFEREOBJVS', 345);
DxfHeaderSpecification.set('$INTERFEREVPVS', 346);
DxfHeaderSpecification.set('$INTERSECTIONCOLOR', 70);
DxfHeaderSpecification.set('$INTERSECTIONDISPLAY', 290);
DxfHeaderSpecification.set('$JOINSTYLE', 280);
DxfHeaderSpecification.set('$LIMCHECK', 70);
DxfHeaderSpecification.set('$LIMMAX', [10, 20]);
DxfHeaderSpecification.set('$LIMMIN', [10, 20]);
DxfHeaderSpecification.set('$LTSCALE', 40);
DxfHeaderSpecification.set('$LUNITS', 70);
DxfHeaderSpecification.set('$LUPREC', 70);
DxfHeaderSpecification.set('$LWDISPLAY', 290);
DxfHeaderSpecification.set('$MAXACTVP', 70);
DxfHeaderSpecification.set('$MEASUREMENT', 70);
DxfHeaderSpecification.set('$MENU', 1);
DxfHeaderSpecification.set('$MIRRTEXT', 70);
DxfHeaderSpecification.set('$OBSCOLOR', 70);
DxfHeaderSpecification.set('$OBSLTYPE', 280);
DxfHeaderSpecification.set('$ORTHOMODE', 70);
DxfHeaderSpecification.set('$PDMODE', 70);
DxfHeaderSpecification.set('$PDSIZE', 40);
DxfHeaderSpecification.set('$PELEVATION', 40);
DxfHeaderSpecification.set('$PEXTMAX', [10, 20, 30]);
DxfHeaderSpecification.set('$PEXTMIN', [10, 20, 30]);
DxfHeaderSpecification.set('$PINSBASE', [10, 20, 30]);
DxfHeaderSpecification.set('$PLIMCHECK', 70);
DxfHeaderSpecification.set('$PLIMMAX', [10, 20]);
DxfHeaderSpecification.set('$PLIMMIN', [10, 20]);
DxfHeaderSpecification.set('$PLINEGEN', 70);
DxfHeaderSpecification.set('$PLINEWID', 40);
DxfHeaderSpecification.set('$PROJECTNAME', 1);
DxfHeaderSpecification.set('$PROXYGRAPHICS', 70);
DxfHeaderSpecification.set('$PSLTSCALE', 70);
DxfHeaderSpecification.set('$PSTYLEMODE', 290);
DxfHeaderSpecification.set('$PSVPSCALE', 40);
DxfHeaderSpecification.set('$PUCSBASE', 2);
DxfHeaderSpecification.set('$PUCSNAME', 2);
DxfHeaderSpecification.set('$PUCSORG', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGBACK', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGBOTTOM', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGFRONT', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGLEFT', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGRIGHT', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORGTOP', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSORTHOREF', 2);
DxfHeaderSpecification.set('$PUCSORTHOVIEW', 70);
DxfHeaderSpecification.set('$PUCSXDIR', [10, 20, 30]);
DxfHeaderSpecification.set('$PUCSYDIR', [10, 20, 30]);
DxfHeaderSpecification.set('$QTEXTMODE', 70);
DxfHeaderSpecification.set('$REGENMODE', 70);
DxfHeaderSpecification.set('$SHADEDGE', 70);
DxfHeaderSpecification.set('$SHADEDIF', 70);
DxfHeaderSpecification.set('$SHADOWPLANELOCATION', 40);
DxfHeaderSpecification.set('$SKETCHINC', 40);
DxfHeaderSpecification.set('$SKPOLY', 70);
DxfHeaderSpecification.set('$SORTENTS', 280);
DxfHeaderSpecification.set('$SPLINESEGS', 70);
DxfHeaderSpecification.set('$SPLINETYPE', 70);
DxfHeaderSpecification.set('$SURFTAB1', 70);
DxfHeaderSpecification.set('$SURFTAB2', 70);
DxfHeaderSpecification.set('$SURFTYPE', 70);
DxfHeaderSpecification.set('$SURFU', 70);
DxfHeaderSpecification.set('$SURFV', 70);
DxfHeaderSpecification.set('$TDCREATE', 40);
DxfHeaderSpecification.set('$TDINDWG', 40);
DxfHeaderSpecification.set('$TDUCREATE', 40);
DxfHeaderSpecification.set('$TDUPDATE', 40);
DxfHeaderSpecification.set('$TDUSRTIMER', 40);
DxfHeaderSpecification.set('$TDUUPDATE', 40);
DxfHeaderSpecification.set('$TEXTSIZE', 40);
DxfHeaderSpecification.set('$TEXTSTYLE', 7);
DxfHeaderSpecification.set('$THICKNESS', 40);
DxfHeaderSpecification.set('$TILEMODE', 70);
DxfHeaderSpecification.set('$TRACEWID', 40);
DxfHeaderSpecification.set('$TREEDEPTH', 70);
DxfHeaderSpecification.set('$UCSBASE', 2);
DxfHeaderSpecification.set('$UCSNAME', 2);
DxfHeaderSpecification.set('$UCSORG', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGBACK', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGBOTTOM', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGFRONT', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGLEFT', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGRIGHT', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORGTOP', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSORTHOREF', 2);
DxfHeaderSpecification.set('$UCSORTHOVIEW', 70);
DxfHeaderSpecification.set('$UCSXDIR', [10, 20, 30]);
DxfHeaderSpecification.set('$UCSYDIR', [10, 20, 30]);
DxfHeaderSpecification.set('$UNITMODE', 70);
DxfHeaderSpecification.set('$USERI1 - 5', 70);
DxfHeaderSpecification.set('$USERR1 - 5', 40);
DxfHeaderSpecification.set('$USRTIMER', 70);
DxfHeaderSpecification.set('$VERSIONGUID', 2);
DxfHeaderSpecification.set('$VISRETAIN', 70);
DxfHeaderSpecification.set('$WORLDVIEW', 70);
DxfHeaderSpecification.set('$XCLIPFRAME', 290);
DxfHeaderSpecification.set('$XEDIT', 290);
