name: CD

on:
  release:
    types: [published]

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run coverage
      - run: bun run build
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          bun publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
